config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/form', to: 'pages#admin'
  get 'producers', to: 'artists#producers'
  get 'songs/originals', to: 'songs#originals'
  get 'songs/instrumentals', to: 'songs#instrumentals'
  get 'riddims/random', to: 'riddims#random'
  resources :songs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :artists, only: [:index, :show, :create, :edit, :update]
  resources :song_artists, only: [:new, :create, :edit, :update, :destroy]
  resources :riddims, only: [:index, :show, :create, :update]
  resources :labels, only: [:index, :show, :create, :edit, :update]
  resources :members, only: [:new, :create, :edit, :update]
end

app/models/label.rb
class Label < ApplicationRecord
  validates_uniqueness_of :name
  belongs_to :founder, class_name: "Artist", foreign_key: :founder_id, optional: true
  belongs_to :parent, class_name: "Label", optional: true
  # has_many :children, class_name: "Label" foreign_key: "parent_id"
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @labels = Label.all.sort_by {|l| l.name}
    @label = Label.new
  end

  def show
    require 'will_paginate/array'
    @label = Label.find(params[:id])
    @children = Label.where(parent_id: @label.id)
    @songs = Song.where(label_id: @label.id).sort_by {|s|s.artists[0].name}.paginate(page: params[:page], per_page: 50)
  end

  def create
    @label = Label.new(label_params)
    @label.save
    redirect_back(fallback_location: root_path)
  end

  def edit
    @label = Label.find(params[:id])
  end

  def update
    @label = Label.find(params[:id])
    @label.update(label_params)
    redirect_to(labels_path)
  end

  def label_params
    params.require(:label).permit(:name, :founder_id, :parent_id)
  end
end

app/views/labels/edit.html.erb
<h1>Edit <%= @label.name %></h1>

<%= simple_form_for(@label) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.association :founder, input_html: {id: 'artist-select' } %>
    <%= f.association :parent, input_html: {id: 'label-select' } %>
  </div>
  <%= f.submit %>
<% end %>

app/views/labels/index.html.erb
<% content_for :meta_title, "Labels index - #{DEFAULT_META["meta_website_name"]}" %>

<h1>Labels (<%=@labels.count%>)</h1>

<div class="flex-between">
  <ul id="labels-list">
  <% @labels.each do |l| %>
    <li class="<%="red" if l.founder.nil? && l.parent.nil? %>"><%= link_to l.name, label_path(l) %></li>
  <% end %>
  </ul>

</div>

app/views/labels/show.html.erb
<% content_for :meta_title, "#{@label.name} - #{DEFAULT_META["meta_website_name"]}" %>

<%= link_to "Edit", edit_label_path(@label), class: "edit" %>
<h1><%= @label.name %></h1>
<% unless @label.founder.nil? %>
  <h5>Founded by <%= link_to @label.founder.name, artist_path(@label.founder) %></h5>
<% end %>

<% unless @label.parent.nil? %>
  <h6>Parent label : <%= link_to @label.parent.name, label_path(@label.parent) %></h6>
<% end %>

<% unless @children.nil? || @children.empty? %>
  <h6>Sub-labels :
    <% @children.each do |child| %>
      <%= link_to child.name, label_path(child) %><%= ", " unless child == @children.last %>
    <% end %>
  </h6>
<% end %>
<%= will_paginate @songs %>
<%= render 'shared/songs_table' unless @songs.empty? %>