config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/form', to: 'pages#admin'
  get 'producers', to: 'artists#producers'
  get 'songs/originals', to: 'songs#originals'
  get 'songs/instrumentals', to: 'songs#instrumentals'
  get 'riddims/random', to: 'riddims#random'
  resources :songs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :artists, only: [:index, :show, :create, :edit, :update]
  resources :song_artists, only: [:new, :create, :edit, :update, :destroy]
  resources :riddims, only: [:index, :show, :create, :update]
  resources :labels, only: [:index, :show, :create, :edit, :update]
  resources :members, only: [:new, :create, :edit, :update]
end

app/views/shared/_add_elements.html.erb
<div class="fixed">
  <div class="add-element">
    <%= simple_form_for(@artist, html: {class: "form"}) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Artist" %>
        <%= f.text_field :name %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="add-element">
    <%= simple_form_for(@label, html: {class: "form"}) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Label" %>
        <%= f.text_field :name %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="add-element">
    <%= simple_form_for(@riddim, html: {class: "form"}) do |f| %>
      <div class="form-group">
        <%= f.label :title, "Riddim" %>
        <%= f.text_field :title %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>

  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="form-add">
  <h3>Add a riddim</h3>
  <%= simple_form_for(@riddim, html: {class: "form d-flex"}) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

<div class="form-add">
  <h3>Add a label</h3>
  <%= simple_form_for(@label, html: {class: "form d-flex"}) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

<div class="form-add">
  <h3>Add an artist</h3>
  <%= simple_form_for(@artist, html: {class: "form d-flex"}) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to "Songs", songs_path %>
  <%= link_to "Riddims", riddims_path %>
  <%= link_to "Labels", labels_path %>
  <%= link_to "Artists", artists_path %>
  <%= link_to "Producers", producers_path %>
  <%= link_to "Add a song", new_song_path %>
  <%= link_to "Members", new_member_path %>
</nav>

app/views/shared/_songs_table.html.erb
<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Song</th>
      <th>Label</th>
      <th>Year</th>
      <th>Riddim</th>
      <th>Producer</th>
      <th>Search</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |s| %>
      <% artist_label = [] %>
      <% s.song_artists.each {|sa| sa.as.nil? || sa.as.empty? ? artist_label << sa.artist.name : artist_label << sa.as } %>
      <tr class="song<%= ' original' if s.original %>">
        <td>
          <% s.song_artists.each do |sa| %>
          <%= link_to sa.as.nil? || sa.as.empty? ? sa.artist.name : sa.as, artist_path(sa.artist) %><%= " & " unless sa == s.song_artists.last %>
          <% end %>
        </td>
        <td><%= s.title %></td>
        <td><%= link_to s.label.name, label_path(s.label) %></td>
        <td><%= s.year %></td>
        <td><%= link_to s.riddim.title, riddim_path(s.riddim) %></td>
        <td><%= link_to s.producer_alias.nil? || s.producer_alias.empty? ? s.producer.name : s.producer_alias, artist_path(s.producer) unless s.producer.nil? %></td>
        <td class="search"><a target="_blank" href="https://www.youtube.com/results?search_query=<%=artist_label.join('+').delete('&')%>+<%= s.title %>"><i class="fab fa-youtube"></i></a></td>
        <td><%= link_to edit_song_path(s) do %>
          <i class="fas fa-edit"></i>
         <% end %> <%= link_to song_path(s), method: :delete, data: { confirm: "Delete #{s.title}?" } do %>
         <i class="fas fa-trash"></i>
         <%end%>
         </td>
      </tr>

    <% end %>
  </tbody>
</table>