config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/form', to: 'pages#admin'
  get 'producers', to: 'artists#producers'
  get 'songs/originals', to: 'songs#originals'
  get 'songs/instrumentals', to: 'songs#instrumentals'
  get 'riddims/random', to: 'riddims#random'
  resources :songs, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :artists, only: [:index, :show, :create, :edit, :update]
  resources :song_artists, only: [:new, :create, :edit, :update, :destroy]
  resources :riddims, only: [:index, :show, :create, :update]
  resources :labels, only: [:index, :show, :create, :edit, :update]
  resources :members, only: [:new, :create, :edit, :update]
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :song_artists, inverse_of: :song, dependent: :destroy
  accepts_nested_attributes_for :song_artists, allow_destroy: true
  has_many :artists, through: :song_artists
  belongs_to :label
  belongs_to :riddim
  belongs_to :producer, class_name: "Artist", foreign_key: :producer_id, optional: true
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show, :instrumentals, :originals]

  def index
    require 'will_paginate/array'
    @songs_total = Song.all.count
    @songs = Song.last(200).reverse.paginate(page: params[:page], per_page: 50)
  end

  def originals
    require 'will_paginate/array'
    @songs = Song.where(original: true).paginate(page: params[:page], per_page: 50)
  end

  def instrumentals
    require 'will_paginate/array'
    @songs = Song.where(instrumental: true).paginate(page: params[:page], per_page: 50)
  end

  def new
    @artist = Artist.new
    @label = Label.new
    @riddim = Riddim.new
    @song = Song.new
    @song.song_artists.build
  end

  def create
    @song = Song.new(song_params)
    @song.save!
    redirect_back(fallback_location: root_path)
  end

  def edit
    @song = Song.find(params[:id])
    @song_artists = SongArtist.where(song_id: @song.id)
  end

  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    redirect_to songs_path
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def song_params
    params.require(:song).permit(:id, :title, :year, :original, :instrumental, :label_id, :riddim_id, :producer_id, :producer_alias,  artist_ids: [], song_artists_attributes: [:id, :as])
  end

end

app/views/songs/_song_artists_form.html.erb
<%= simple_form_for(@song_artist, html: {class: "form"}) do |f| %>
  <%= f.association :artist %>

  <%= f.simple_fields_for :song, Song.new do |s| %>
    <%= s.input :title %>
    <%= s.association :label, collection: Label.order('name ASC') %>
    <%= s.input :year, as: :numeric %>
    <%= s.association :riddim, collection: Riddim.order('title ASC') %>
    <%= s.association :producer, collection: Artist.order('name ASC') %>
    <%= s.label :original %>
    <%= s.check_box :original %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/songs/_song_form.html.erb
<%= simple_form_for(@song, html: {class: "form"}) do |f| %>

  <%= f.association :artists, label: "Artists", include_blank: false, include_hidden: false, input_html: {id: 'artist-select', multiple: true } %>
  <% unless @song.artist_ids.empty? %>
    <%= f.fields_for :song_artists do |sa| %>
      <%= sa.input :as, label: "Alias for #{sa.object.artist.name}" %>
    <% end %>
  <% end %>
  <%= f.input :title %>
  <%= f.association :label, input_html: {id: 'label-select'} %>
  <% %>
  <%= f.input :year, as: :numeric %>
  <%= f.association :riddim, input_html: {id: 'riddim-select'} %>
  <%= f.association :producer, input_html: {id: 'producer-select'} %>
  <%= f.input :producer_alias, label: "As" %>
  <%= f.check_box :original %>
  <%= f.label :original %>
  <br>
  <%= f.check_box :instrumental %>
  <%= f.label :instrumental %>
  <br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit song</h1>

<%= render 'song_form' %>

app/views/songs/index.html.erb
<% content_for :meta_title, "Songs index - #{DEFAULT_META["meta_website_name"]}" %>

<h1>Songs Index (<%=@songs_total%>)</h1>
<div class="top-right">
<%= link_to 'Original Songs', songs_originals_path %>
<%= link_to 'Instrumentals', songs_instrumentals_path %>
</div>

<%= will_paginate @songs %>
<%= render 'shared/songs_table' %>
<%= will_paginate @songs %>

app/views/songs/instrumentals.html.erb
<% content_for :meta_title, "Instrumentals - #{DEFAULT_META["meta_website_name"]}" %>

<h1>Instrumentals (<%=@songs.count%>)</h1>

<%= will_paginate @songs %>
<%= render 'shared/songs_table' %>

app/views/songs/new.html.erb
<% content_for :meta_title, "New song - #{DEFAULT_META["meta_website_name"]}" %>

<h1>New song</h1>

<%= render 'shared/add_elements' %>
<%= render 'song_form' %>

app/views/songs/originals.html.erb
<% content_for :meta_title, "Original songs - #{DEFAULT_META["meta_website_name"]}" %>

<h1>Original Songs (<%=@songs.count%>)</h1>

<%= will_paginate @songs %>
<%= render 'shared/songs_table' %>